### ISSUE TITLE
Cannot use the debugger with Krom

### ISSUE THREAD

**Issue by FuriouZz** [KTXSoftware/vscode-krom-debug#3]
I got this error when I run the debug with Krom.

![screenshot_2](https://user-images.githubusercontent.com/1800468/44310015-c0065b80-a3cf-11e8-86cd-3bf35622a8a6.png)

- VS Code Version: 1.26

Steps to reproduce:

1. Select Kha: Krom
2. Debug Kha: Krom

**Comment by RobDangerous** [comment]
Should work now.
